### ISSUE TITLE
Consider removing .NET binaries from GitHub

### ISSUE THREAD

**Issue by garys-esri** [garys-esri/geodev-dc-labs#34]
Directories like this:

https://github.com/garys-esri/geodev-dc-labs/tree/master/2016-11-runtime/solutions/dotNetWPF/Ex1_MapAndScene/Ex1_MapAndScene/bin/Debug

and this:

https://github.com/garys-esri/geodev-dc-labs/tree/master/2016-11-runtime/solutions/dotNetWPF/Ex1_MapAndScene/Ex1_MapAndScene/obj/Debug

typically don't belong in GitHub. Is there a good reason to include them? If not, we should 1) remove them and 2) use a .gitignore file to ignore them.

**Comment by jofraley** [comment]
I have removed the files and folders that should not be there and also updated the .gitignore file.
